### ISSUE TITLE
Create and execute user interview approach

### ISSUE THREAD

**Issue by aassoiants** [bitcoin-dev-project/sim-ln#107]
- [x] Create script
- [ ] Prepare assets
- [ ] Recruit participants
- [ ] Hold interviews
- [ ] Run insights summary session
- [ ] Implement findings

**Comment by aassoiants** [comment]
@carlaKC will need your help padding out questions/ specifics for the 3 steps in this proposed [interview feedback script](https://docs.google.com/document/d/12oZDi_GZCyBa4whdkTPm1saJkM4TE2kKa1JmPgR0-5o).

**Comment by aassoiants** [comment]
Thanks for the review @carlaKC!

When do you think the soonest feasible user interview can happen? This will help me plan w other projects.

**Comment by carlaKC** [comment]
> When do you think the soonest feasible user interview can happen? This will help me plan w other projects.

Monday/Tuesday if that suits?

**Comment by carlaKC** [comment]
Is this a sub-task of #109? As in, do [these questions](https://github.com/bitcoin-dev-project/sim-ln/issues/109#issuecomment-1730219973) need to go into the script?

**Comment by aassoiants** [comment]
They can if we combine the two!

The original plan was to send the #109 questions async for feedback from people we'd already spoken to. 

But if we're planning to run end-to-end user flow tests, then can embed those random activity generator Qs there as well. 

Or do both - as the activity gen Qs in the user tests but also send for async replies from people we won't be interviewing

**Comment by carlaKC** [comment]
> The original plan was to send the https://github.com/bitcoin-dev-project/sim-ln/issues/109 questions async for feedback from people we'd already spoken to.

Ah got it! 

> Or do both - ask the activity gen Qs in the user tests but also send for async replies from people we won't be interviewing

Like that:
* 109: send out async to everyone we've interviewed so far.
* 107: incorporate some specific random generation questions in interviews (I have some new folks I'd like to include).

**Comment by aassoiants** [comment]
Yes exactly! 

Let's tackle the question of research implementation tomo (who to recruit, when to hold it, and the like)

**Comment by carlaKC** [comment]
Completed in 3x new user interviews!

**Comment by aassoiants** [comment]
Yahoo!
