### ISSUE TITLE
Create and implement a release communications strategy

### ISSUE THREAD

**Issue by aassoiants** [bitcoin-dev-project/sim-ln#108]
- [ ] Where will we post
- [ ] What copy do we want to use
- [ ] Some copy about the connection to and difference from polar/ scaling
- [ ] Timelines
- [ ] Way for people to provide feedback outside of GitHub issues

**Comment by carlaKC** [comment]
> Way for people to provide feedback outside of GitHub issues

I think it _could_ be worth trying to steer people towards GH discussions for the "user support" class of questions that are unlikely to be serious enough to get somebody to open up an issue. I like that they're searchable, and easier to manage than something like a discord server.

**Comment by aassoiants** [comment]
Haven't used GH Discussions and am open to trying! Def don't think a Discord makes sense at this point. 

From a user friction point of view, the feedback funnel can look something like
1. Inviting folks to reply to news thread with suggestions, concerns, bugs, questions
2. GH Discussions
3. Open up a GitHub

**Comment by aassoiants** [comment]
Drafted a [rough skeleton](https://docs.google.com/document/d/1K4mCYdjArL8FMpRwyv9UUyLxGAFzE6OaJDDtTa8Em0Y/edit) for the launch plan - would like your reaction @carlaKC @adamjonas

**Comment by carlaKC** [comment]
Completed in various docs (so far as I know)!
