### ISSUE TITLE
Get feedback on random activity generator feature

### ISSUE THREAD

**Issue by aassoiants** [bitcoin-dev-project/sim-ln#109]
- [ ] Align on what questions to ask
- [ ] Create feedback assets
- [ ] Send to participants
- [ ] Summarize and discuss insights
- [ ] Implement findings

**Comment by carlaKC** [comment]
Some questions to ask (based on #111, which may be subject to change), we can phrase nicely but key ideas I'd like to hit are: 
- Would you forsee yourself using random activity, predefined user-generated activity or a combination of both?
- If using random activity, would it be important to have some nodes that do not send any payments and operate only as routing nodes?
- Is "multiplier on capacity" an intuitive way to express the level of "business" in the network?
- When using a tool like this, is the size of payment that it is generating particularly important to you?
- Are there any types of activity that are important to you to see? For example, big->big node, small -> big etc. 

Will drop more in as they come!

**Comment by aassoiants** [comment]
Great!

I think something as simple as a 1 min Loom video could be good to set context. "Here's what we're working on. Here's what the random activity generator would do." 

Then just include these questions as a follow up. 

Really low effort but since already spoke with some of these people, might work really well
