### ISSUE TITLE
Update image and copy on link preview

### ISSUE THREAD

**Issue by aassoiants** [bitcoin-dev-project/sim-ln#115]
When users post the link in things like Discord, the preview should have a representative image and copy. 

Let's use this copy: "Instantly simulate real-world Lightning network activity"

Please use this as aesthetic inspiration, but not the image itself: 
![image](https://github.com/bitcoin-dev-project/sim-ln/assets/126297088/b90e221e-5c24-4507-b896-459680d67e5c)

CC @carlaKC

**Comment by carlaKC** [comment]
@Emmanuel-Develops would you be able to pick this up?

**Comment by Emmanuel-Develops** [comment]
> @Emmanuel-Develops would you be able to pick this up?

yeah sure!

**Comment by Emmanuel-Develops** [comment]
I drew up something quick on figma. The image, description and title is tied to this preview link:
https://sim-44sgf2y0n-btc-knowledge-base.vercel.app/
I'm a bit conflicted on how the image looks in small previews

if stephan gets some free time perhaps he could draw up one on figma

cc: @aassoiants

**Comment by Emmanuel-Develops** [comment]
closed by https://github.com/bitcoin-dev-project/sim-ln-website/pull/1
