### ISSUE TITLE
Product: Update copy on website

### ISSUE THREAD

**Issue by carlaKC** [bitcoin-dev-project/sim-ln#119]
The copy on the site needs updating to the latest version - the landing page and getting started sections are written up [here](https://docs.google.com/document/d/1SgxXh8Y8zUIX-eucynmUK6sI1dcenXJCKicIi94V6oc/edit?usp=sharing).

**Comment by carlaKC** [comment]
@Emmanuel-Develops would you be able to pick this one up as well? 🙏

**Comment by Emmanuel-Develops** [comment]
> @Emmanuel-Develops would you be able to pick this one up as well? 🙏

sure!

**Comment by carlaKC** [comment]
Thank you!!

**Comment by Emmanuel-Develops** [comment]
> Thank you!!

Pr here:
https://github.com/bitcoin-dev-project/sim-ln-website/pull/2

preview link here:
https://sim-cyuzj62pf-btc-knowledge-base.vercel.app/
