### ISSUE TITLE
Feature Request: Image in docker hub

### ISSUE THREAD

**Issue by m3dwards** [bitcoin-dev-project/sim-ln#138]
I would love to have an image in docker hub so that I don't have to build SimLN myself. I personally use both ARM and x86 architectures and I think these two are good as a starting point for images.

I have twice (Torq + Scaling Lightning) made multi-architecture docker builds that upload to docker hub on a tag and on a github release so please feel free to take a look at the scaling repo to see how I tackled it.

I'm also happy to contribute or talk through how it works in the projects I've done it for; Torq and Scaling do it two different ways.

**Comment by sr-gi** [comment]
It's been a while, but I've managed to do this before too for multi-arch. Happy to give it a look/chat if necessary to tackle this.

**Comment by maxwedwards** [comment]
@sr-gi would you mind me picking this up?

**Comment by sr-gi** [comment]
@maxwedwards not at all. Feel free
