### ISSUE TITLE
Robustness: Validate node networks and disallow mainnet

### ISSUE THREAD

**Issue by carlaKC** [bitcoin-dev-project/sim-ln#29]
When we're given a set of nodes, we should validate that they're all on the same network. We don't need to worry about destinations / activity, since we check this against the graph but it's _possible_ that somebody accidentally configures nodes on different networks.

We should also completely disallow mainnet while we're here, since this is a testing tool that slings money around with abandon.

**Comment by Extheoisah** [comment]
sure 😁
